const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0]
const dayAfter = new Date(Date.now() + 2 * 86400000).toISOString().split('T')[0]

export const DEMO_DRIVERS = [
  {
    name: 'Dawit Tesfaye',
    current_city: 'Atlanta',
    current_state: 'GA',
    current_lat: 33.749,
    current_lng: -84.388,
    hos_remaining_hours: 9.5,
    truck_type: 'Freightliner Cascadia',
    trailer_type: 'Dry Van',
    available: true,
    mc_number: 'MC-845721',
    phone: '555-0101',
  },
  {
    name: 'Gurpreet Singh',
    current_city: 'Dallas',
    current_state: 'TX',
    current_lat: 32.777,
    current_lng: -96.797,
    hos_remaining_hours: 7.0,
    truck_type: 'Kenworth T680',
    trailer_type: 'Reefer',
    available: true,
    mc_number: 'MC-923456',
    phone: '555-0102',
  },
  {
    name: 'Bobby Ray Crawford',
    current_city: 'Memphis',
    current_state: 'TN',
    current_lat: 35.15,
    current_lng: -90.049,
    hos_remaining_hours: 11.0,
    truck_type: 'International LT',
    trailer_type: 'Dry Van',
    available: true,
    mc_number: 'MC-498765',
    phone: '555-0105',
  },
  {
    name: 'Andrey Petrov',
    current_city: 'Chicago',
    current_state: 'IL',
    current_lat: 41.878,
    current_lng: -87.63,
    hos_remaining_hours: 10.0,
    truck_type: 'Peterbilt 579',
    trailer_type: 'Dry Van',
    available: true,
    mc_number: 'MC-712389',
    phone: '555-0103',
  },
  {
    name: 'Miguel Contreras',
    current_city: 'Los Angeles',
    current_state: 'CA',
    current_lat: 34.052,
    current_lng: -118.244,
    hos_remaining_hours: 8.5,
    truck_type: 'Volvo VNL 860',
    trailer_type: 'Flatbed',
    available: true,
    mc_number: 'MC-654321',
    phone: '555-0104',
  },
]

export function buildDemoLoads(brokerPhone = '+16169479297') {
  return [
    { origin_city: 'Atlanta', origin_state: 'GA', origin_lat: 33.749, origin_lng: -84.388, dest_city: 'Dallas', dest_state: 'TX', dest_lat: 32.777, dest_lng: -96.797, posted_rate: 3200, rate_per_mile: 4.1, broker_name: 'TQL Logistics', broker_phone: brokerPhone, equipment_type: 'Dry Van', weight: 42000, miles: 780, pickup_date: tomorrow, status: 'available', source: 'DAT', collected: false, assigned_driver_id: null },
    { origin_city: 'Chicago', origin_state: 'IL', origin_lat: 41.878, origin_lng: -87.63, dest_city: 'Memphis', dest_state: 'TN', dest_lat: 35.15, dest_lng: -90.049, posted_rate: 2100, rate_per_mile: 4.2, broker_name: 'CH Robinson', broker_phone: brokerPhone, equipment_type: 'Dry Van', weight: 38000, miles: 500, pickup_date: tomorrow, status: 'available', source: 'DAT', collected: false, assigned_driver_id: null },
    { origin_city: 'Los Angeles', origin_state: 'CA', origin_lat: 34.052, origin_lng: -118.244, dest_city: 'Phoenix', dest_state: 'AZ', dest_lat: 33.449, dest_lng: -112.074, posted_rate: 1800, rate_per_mile: 4.74, broker_name: 'Echo Global', broker_phone: brokerPhone, equipment_type: 'Flatbed', weight: 35000, miles: 380, pickup_date: dayAfter, status: 'available', source: 'DAT', collected: false, assigned_driver_id: null },
    { origin_city: 'Dallas', origin_state: 'TX', origin_lat: 32.777, origin_lng: -96.797, dest_city: 'Atlanta', dest_state: 'GA', dest_lat: 33.749, dest_lng: -84.388, posted_rate: 3100, rate_per_mile: 3.97, broker_name: 'XPO Logistics', broker_phone: brokerPhone, equipment_type: 'Dry Van', weight: 44000, miles: 780, pickup_date: tomorrow, status: 'available', source: 'DAT', collected: false, assigned_driver_id: null },
    { origin_city: 'Memphis', origin_state: 'TN', origin_lat: 35.15, origin_lng: -90.049, dest_city: 'Chicago', dest_state: 'IL', dest_lat: 41.878, dest_lng: -87.63, posted_rate: 2050, rate_per_mile: 4.1, broker_name: 'Coyote Logistics', broker_phone: brokerPhone, equipment_type: 'Dry Van', weight: 40000, miles: 500, pickup_date: dayAfter, status: 'available', source: 'DAT', collected: false, assigned_driver_id: null },
    { origin_city: 'Atlanta', origin_state: 'GA', origin_lat: 33.749, origin_lng: -84.388, dest_city: 'Miami', dest_state: 'FL', dest_lat: 25.762, dest_lng: -80.192, posted_rate: 1950, rate_per_mile: 2.93, broker_name: 'Landstar', broker_phone: brokerPhone, equipment_type: 'Reefer', weight: 36000, miles: 665, pickup_date: tomorrow, status: 'available', source: 'DAT', collected: false, assigned_driver_id: null },
    { origin_city: 'Houston', origin_state: 'TX', origin_lat: 29.76, origin_lng: -95.37, dest_city: 'Dallas', dest_state: 'TX', dest_lat: 32.777, dest_lng: -96.797, posted_rate: 850, rate_per_mile: 3.4, broker_name: 'Werner Logistics', broker_phone: brokerPhone, equipment_type: 'Dry Van', weight: 30000, miles: 250, pickup_date: tomorrow, status: 'available', source: 'DAT', collected: false, assigned_driver_id: null },
    { origin_city: 'Chicago', origin_state: 'IL', origin_lat: 41.878, origin_lng: -87.63, dest_city: 'Dallas', dest_state: 'TX', dest_lat: 32.777, dest_lng: -96.797, posted_rate: 2400, rate_per_mile: 2.53, broker_name: 'JB Hunt Transport', broker_phone: brokerPhone, equipment_type: 'Dry Van', weight: 43000, miles: 950, pickup_date: tomorrow, status: 'available', source: 'DAT', collected: false, assigned_driver_id: null },
    { origin_city: 'Los Angeles', origin_state: 'CA', origin_lat: 34.052, origin_lng: -118.244, dest_city: 'Dallas', dest_state: 'TX', dest_lat: 32.777, dest_lng: -96.797, posted_rate: 3200, rate_per_mile: 2.33, broker_name: 'Convoy', broker_phone: brokerPhone, equipment_type: 'Dry Van', weight: 40000, miles: 1375, pickup_date: dayAfter, status: 'available', source: 'DAT', collected: false, assigned_driver_id: null },
    { origin_city: 'Dallas', origin_state: 'TX', origin_lat: 32.777, origin_lng: -96.797, dest_city: 'Chicago', dest_state: 'IL', dest_lat: 41.878, dest_lng: -87.63, posted_rate: 2200, rate_per_mile: 2.32, broker_name: 'Uber Freight', broker_phone: brokerPhone, equipment_type: 'Reefer', weight: 38000, miles: 950, pickup_date: tomorrow, status: 'available', source: 'DAT', collected: false, assigned_driver_id: null },
    { origin_city: 'Memphis', origin_state: 'TN', origin_lat: 35.15, origin_lng: -90.049, dest_city: 'Atlanta', dest_state: 'GA', dest_lat: 33.749, dest_lng: -84.388, posted_rate: 800, rate_per_mile: 2.11, broker_name: 'Total Quality', broker_phone: brokerPhone, equipment_type: 'Dry Van', weight: 35000, miles: 380, pickup_date: dayAfter, status: 'available', source: 'DAT', collected: false, assigned_driver_id: null },
    { origin_city: 'Phoenix', origin_state: 'AZ', origin_lat: 33.449, origin_lng: -112.074, dest_city: 'Los Angeles', dest_state: 'CA', dest_lat: 34.052, dest_lng: -118.244, posted_rate: 900, rate_per_mile: 2.37, broker_name: 'RXO', broker_phone: brokerPhone, equipment_type: 'Flatbed', weight: 32000, miles: 380, pickup_date: tomorrow, status: 'available', source: 'DAT', collected: false, assigned_driver_id: null },
    { origin_city: 'Atlanta', origin_state: 'GA', origin_lat: 33.749, origin_lng: -84.388, dest_city: 'Chicago', dest_state: 'IL', dest_lat: 41.878, dest_lng: -87.63, posted_rate: 1800, rate_per_mile: 2.47, broker_name: 'Transplace', broker_phone: brokerPhone, equipment_type: 'Dry Van', weight: 41000, miles: 730, pickup_date: dayAfter, status: 'available', source: 'DAT', collected: false, assigned_driver_id: null },
    { origin_city: 'Houston', origin_state: 'TX', origin_lat: 29.76, origin_lng: -95.37, dest_city: 'Memphis', dest_state: 'TN', dest_lat: 35.15, dest_lng: -90.049, posted_rate: 1200, rate_per_mile: 2.09, broker_name: 'Arrive Logistics', broker_phone: brokerPhone, equipment_type: 'Dry Van', weight: 39000, miles: 575, pickup_date: tomorrow, status: 'available', source: 'DAT', collected: false, assigned_driver_id: null },
  ]
}
